---
- name: Converge
  hosts: all

  pre_tasks:

    - name: Update apt cache
      apt:
        cache_valid_time: 600
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Clear out repo for Fedora
      set_fact:
        redis_enablerepo: ""
      when: ansible_distribution == 'Fedora'

  roles:
    - role: proxy-common
